# Generated by Django 5.2.7 on 2025-11-07 15:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('van', models.IntegerField(db_column='VAN', primary_key=True, serialize=False, unique=True)),
                ('vin', models.CharField(blank=True, db_column='VIN', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='VIN must be 11–17 characters (alphanumeric, excluding I/O/Q).', regex='^[A-HJ-NPR-Z0-9]{11,17}$')])),
                ('plate', models.CharField(blank=True, db_column='MATRICULA', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='License plate should be 5–15 chars (letters/digits/hyphens/spaces).', regex='^[A-Z0-9\\- ]{5,15}$')])),
                ('registration_date', models.DateField(blank=True, db_column='DATA_MATRICULA', null=True)),
                ('lot', models.IntegerField(blank=True, db_column='LOT', null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=255, null=True)),
                ('production_year', models.DateField(blank=True, db_column='ANO_PROD', null=True)),
                ('has_service_campaign', models.BooleanField(blank=True, db_column='CAMPANHA_SERVICE', default=False, null=True)),
                ('service_campaign_date', models.DateField(blank=True, db_column='CAMPANHA_SERVICE_DATA', null=True)),
                ('service_campaign_due', models.DateField(blank=True, db_column='CAMPANHA_SERVICE_PREV', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'vehicle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.CharField(db_column='Cliente_Codice', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='Cliente_Nome', max_length=200)),
                ('nif', models.CharField(blank=True, db_column='NIF', help_text='Portuguese taxpayer number (9 digits).', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='NIF must be 9 digits.', regex='^\\d{9}$')])),
                ('address', models.CharField(blank=True, db_column='Morada', max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='Cod_Postal', max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Postal code must be NNNN-NNN.', regex='^\\d{4}-\\d{3}$')])),
                ('city', models.CharField(blank=True, db_column='Localidade', max_length=120, null=True)),
                ('phone', models.CharField(blank=True, db_column='Tel_geral', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^[0-9+\\-\\s().]{7,20}$')])),
                ('email', models.EmailField(blank=True, db_column='Mail_geral', max_length=254, null=True)),
                ('distributor', models.CharField(blank=True, db_column='Distribuidor', max_length=120, null=True)),
                ('seller', models.CharField(blank=True, db_column='Vendedor', max_length=120, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='Ultimo_Atualizar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='client_Cliente_bb5e91_idx'), models.Index(fields=['code'], name='client_Cliente_045b58_idx'), models.Index(fields=['nif'], name='client_NIF_b88d97_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('nif__isnull', False)), fields=('nif',), name='uniq_client_nif_not_null')],
            },
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor', models.CharField(blank=True, db_column='DISTRIBUIDOR', max_length=255, null=True)),
                ('active', models.BooleanField(db_column='ATIVO', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account for this salesperson.', on_delete=django.db.models.deletion.CASCADE, related_name='salesperson_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salesperson',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='OCFStock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('has_client', models.BooleanField(db_column='OCF', default=False, help_text='True if vehicle assigned to a client')),
                ('client_assigned_date', models.DateField(blank=True, db_column='OCF_DATA', null=True)),
                ('channel', models.CharField(blank=True, db_column='CANAL', max_length=255, null=True)),
                ('distributor', models.CharField(blank=True, db_column='DISTRIBUIDOR', max_length=255, null=True)),
                ('order_week', models.IntegerField(blank=True, db_column='SEMANA', help_text='Week number of order', null=True)),
                ('order_date', models.DateField(blank=True, db_column='DATA', null=True)),
                ('order_number', models.IntegerField(blank=True, db_column='NUMERO LATERAL', null=True)),
                ('client_name', models.CharField(blank=True, db_column='CLIENTE', max_length=255, null=True)),
                ('client_final', models.CharField(blank=True, db_column='CLIENTE3', max_length=255, null=True)),
                ('sold', models.BooleanField(db_column='VENDIDO', default=False)),
                ('produced', models.BooleanField(db_column='PRODUZIDO', default=False)),
                ('buyback', models.BooleanField(db_column='BB', default=False)),
                ('extended_warranty', models.BooleanField(db_column='EW', default=False)),
                ('extended_warranty_date', models.DateField(blank=True, db_column='EW_DATA', null=True)),
                ('maintenance_contract', models.BooleanField(db_column='CMR', default=False)),
                ('maintenance_contract_date', models.DateField(blank=True, db_column='CMR_DATA', null=True)),
                ('delivery_date', models.DateField(blank=True, db_column='DATA ENTREGA', null=True)),
                ('expected_delivery', models.CharField(blank=True, db_column='ENTREGA_PREVISTA', max_length=255, null=True)),
                ('reservation_info', models.CharField(blank=True, db_column='RESERVA', max_length=255, null=True)),
                ('reservation_notes', models.TextField(blank=True, db_column='RESERVA_NOTAS', null=True)),
                ('reservation_date', models.DateField(blank=True, db_column='DATA RESERVA', null=True)),
                ('location', models.CharField(blank=True, db_column='LOCALIZAÇÃO', max_length=255, null=True)),
                ('location_date', models.DateField(blank=True, db_column='LOCAL_DATA', null=True)),
                ('warranty_start', models.DateField(blank=True, db_column='WSD', null=True)),
                ('pre_pdi_date', models.DateField(blank=True, db_column='DATA_PRE_PDI', null=True)),
                ('pdi_request_date', models.DateField(blank=True, db_column='DATA_PDI_PEDIDO', null=True)),
                ('pdi_completed_date', models.DateField(blank=True, db_column='DATA_PDI_OK', null=True)),
                ('pdi_notes', models.TextField(blank=True, db_column='NOTAS_PDI', null=True)),
                ('pdi_workshop', models.CharField(blank=True, db_column='OFICINA_PDI', max_length=255, null=True)),
                ('has_service_campaign', models.BooleanField(db_column='CAMPANHA_SERVICE', default=False)),
                ('service_campaign_date', models.DateField(blank=True, db_column='CAMPANHA_SERVICE_DATA', null=True)),
                ('service_campaign_due', models.DateField(blank=True, db_column='CAMPANHA_SERVICE_PREV', null=True)),
                ('notes', models.TextField(blank=True, db_column='NOTAS', null=True)),
                ('stock_notes', models.TextField(blank=True, db_column='Notas_STOCK', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(blank=True, db_column='VENDEDOR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocf_sales', to='Encomenda_Veiculos.salesperson')),
                ('vehicle', models.OneToOneField(db_column='VAN', help_text='The vehicle tracked in OCF stock.', on_delete=django.db.models.deletion.CASCADE, related_name='ocf_entry', to='Encomenda_Veiculos.vehicle')),
            ],
            options={
                'db_table': 'ocf_stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalTransport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, db_column='ORIGEM', max_length=255, null=True)),
                ('destination', models.CharField(blank=True, db_column='DESTINO', max_length=255, null=True)),
                ('request_date', models.DateField(blank=True, db_column='DATA PEDIDO', null=True)),
                ('transport_date', models.DateField(blank=True, db_column='DATA TRANSPORTE', null=True)),
                ('notes', models.TextField(blank=True, db_column='NOTAS', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, db_column='VAN', help_text='Vehicle (by VAN) used for this internal transport.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_transports', to='Encomenda_Veiculos.vehicle')),
            ],
            options={
                'db_table': 'internal_transport',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='VP',
            fields=[
                ('vp_code', models.CharField(db_column='VP Codice', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('variant', models.CharField(blank=True, db_column='Variante', max_length=255, null=True)),
                ('version', models.CharField(blank=True, db_column='Versão', max_length=255, null=True)),
                ('homologation', models.CharField(blank=True, db_column='Homologação', max_length=255, null=True)),
                ('co2', models.IntegerField(blank=True, db_column='CO2', null=True)),
                ('tare_kg', models.IntegerField(blank=True, db_column='TARA', null=True)),
                ('engine_code', models.CharField(blank=True, db_column='Motore_V', max_length=255, null=True)),
                ('gama', models.CharField(blank=True, db_column='GAMA', max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, db_column='MODELO', max_length=255, null=True)),
                ('cabina', models.CharField(blank=True, db_column='CABINA', max_length=255, null=True)),
                ('motor', models.CharField(blank=True, db_column='MOTOR', max_length=255, null=True)),
                ('gearbox', models.CharField(blank=True, db_column='CAIXA VEL', max_length=255, null=True)),
                ('wheelbase', models.CharField(blank=True, db_column='WB', max_length=255, null=True)),
                ('dee', models.IntegerField(blank=True, db_column='DEE', null=True)),
                ('hi', models.CharField(blank=True, db_column='HI', max_length=255, null=True)),
                ('color_code_numeric', models.IntegerField(blank=True, db_column='Colore_Codice (Numerico)', null=True)),
                ('color_desc', models.CharField(blank=True, db_column='Colore_Descrizione Estesa', max_length=255, null=True)),
                ('notas_vp', models.TextField(blank=True, db_column='NOTAS_VP', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'vp',
                'ordering': ['vp_code'],
                'indexes': [models.Index(fields=['vp_code'], name='vp_VP Codi_2e0294_idx'), models.Index(fields=['modelo', 'version'], name='vp_MODELO_37b05b_idx')],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vp',
            field=models.ForeignKey(db_column='VP_FK', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='Encomenda_Veiculos.vp'),
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Contact person name.', max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^[0-9+\\-\\s().]{7,20}$')])),
                ('is_primary', models.BooleanField(default=False, help_text='Marks this as the primary contact for the client.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Owning client.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Encomenda_Veiculos.client')),
            ],
            options={
                'verbose_name': 'Client Contact',
                'verbose_name_plural': 'Client Contacts',
                'db_table': 'client_contact',
                'ordering': ['client_id', 'name'],
                'indexes': [models.Index(fields=['client', 'name'], name='client_cont_client__8667ae_idx'), models.Index(fields=['client', 'email'], name='client_cont_client__13ded0_idx'), models.Index(fields=['client', 'phone'], name='client_cont_client__6c5ebb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('client', 'email'), name='uniq_client_contact_email'), models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('client', 'phone'), name='uniq_client_contact_phone'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('client', 'is_primary'), name='uniq_client_primary_contact')],
            },
        ),
        migrations.AddIndex(
            model_name='salesperson',
            index=models.Index(fields=['distributor'], name='salesperson_DISTRIB_737403_idx'),
        ),
        migrations.AddIndex(
            model_name='salesperson',
            index=models.Index(fields=['active'], name='salesperson_ATIVO_550422_idx'),
        ),
        migrations.AddIndex(
            model_name='ocfstock',
            index=models.Index(fields=['has_client'], name='ocf_stock_OCF_dfdeee_idx'),
        ),
        migrations.AddIndex(
            model_name='ocfstock',
            index=models.Index(fields=['sold'], name='ocf_stock_VENDIDO_2b991b_idx'),
        ),
        migrations.AddIndex(
            model_name='ocfstock',
            index=models.Index(fields=['produced'], name='ocf_stock_PRODUZI_f17b26_idx'),
        ),
        migrations.AddIndex(
            model_name='ocfstock',
            index=models.Index(fields=['delivery_date'], name='ocf_stock_DATA EN_1d9263_idx'),
        ),
        migrations.AddIndex(
            model_name='ocfstock',
            index=models.Index(fields=['salesperson'], name='ocf_stock_VENDEDO_a34ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='internaltransport',
            index=models.Index(fields=['vehicle', 'transport_date'], name='internal_tr_VAN_402172_idx'),
        ),
        migrations.AddIndex(
            model_name='internaltransport',
            index=models.Index(fields=['origin'], name='internal_tr_ORIGEM_c3c356_idx'),
        ),
        migrations.AddIndex(
            model_name='internaltransport',
            index=models.Index(fields=['destination'], name='internal_tr_DESTINO_d8eb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['van'], name='vehicle_VAN_f0e9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vehicle_VIN_c50fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate'], name='vehicle_MATRICU_e5c895_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vp'], name='vehicle_VP_FK_f8c08a_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('vin__isnull', False)), fields=('vin',), name='uniq_vehicle_vin_nn'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('plate__isnull', False)), fields=('plate',), name='uniq_vehicle_plate_nn'),
        ),
    ]
